package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Casino")
    void generatedTest() {
        step("Open  http://test-app.d6.dev.devcaz.com/admin/login", () -> {
            step("// todo: just add selenium action");
        });

        step("Set username \"admin1\"", () -> {
            step("// todo: just add selenium action");
        });

        step("Set password \"[9k<k8^z!+$$GkuP\"", () -> {
            step("// todo: just add selenium action");
        });

        step("Check that the user is successfully authorized, the admin panel has loaded", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'http://test-app.d6.dev.devcaz.com/admin/login'", () ->
            open("http://test-app.d6.dev.devcaz.com/admin/login"));

        step("Page title should have text 'Dashboard - Casino'", () -> {
            String expectedTitle = "Dashboard - Casino";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'http://test-app.d6.dev.devcaz.com/admin/login'", () ->
            open("http://test-app.d6.dev.devcaz.com/admin/login"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}